baseURL = 'https://erg0nix.github.io/'
languageCode = 'en-us'
title = 'erg0nix'
publishDir = 'public'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "github-dark"
lineNos = true
lineNumbersInTable = false
tabWidth = 2

[outputs]
home = ["HTML", "RSS"]
